[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "https://quickcards.shop/*"
  to = "https://quickcardshop.com/:splat"
  status = 301
  force = true
