window.products = [
  {
    "id": 1,
    "name": "Shohei Ohtani #PAS-9 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/bewAAeSwPMBpz96~/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168284283557",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 2,
    "name": "PSA 6 - Bulbasaur Ivysaur Venusaur Pokémon Blue Logo Topps Sticker First *BTX",
    "price": 10,
    "image": "https://i.ebayimg.com/images/g/k8IAAeSwZwBpo0L4/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497246",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 3,
    "name": "2024 Topps Now MLB #815 Fernando Tatis Jr. San Diego Padres NLDS",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/98UAAOSw~OFnB1pS/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245476308",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 4,
    "name": "1989 Topps Nintendo Super Macho Man Punch-Out Game Tip Sticker PSA 7  *BTX",
    "price": 10,
    "image": "https://i.ebayimg.com/images/g/ZDoAAeSweR9pg8iL/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497249",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 5,
    "name": "Shohei Ohtani #58 Base Card - 2025 Stadium Club - MLB Baseball",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/OLkAAeSw779pqjTD/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168208986722",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 6,
    "name": "Shoehei Ohtani #BTP-3 - 2026 Topps Series 1 - MLB Baseball",
    "price": 2,
    "image": "https://i.ebayimg.com/images/g/WeMAAeSwIpVpleLS/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168304893207",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 7,
    "name": "Lane Thomas #285 CHROME - 2026 Topps Heritage MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/dVkAAeSw0SNpxG3a/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168262690838",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 8,
    "name": "Blake Snell 10Ks Makes MLB History - 2025 MLB Topps NOW® - Card 867",
    "price": 2.5,
    "image": "https://i.ebayimg.com/images/g/E8cAAeSwnqBo7o5h/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307220752",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 9,
    "name": "Jayden Daniels - 2024 Topps NOW® Football Card 19 NFL Commanders",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/fb0AAOSw57RnczOJ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245503771",
    "category": "football",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 10,
    "name": "Addison Barger - 1st Ever Pinch GS - 2025 MLB Topps NOW® - Card 897 #a",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/HkIAAeSwIrFo~Sw1/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039209",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 11,
    "name": "AUTO Kyle Karros (RC) #ROA-KK  - 2026 Heritage - MLB Baseball Card",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/~akAAeSwtV5p3rSl/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168309074764",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 12,
    "name": "SPRUNKI Incredibox - 55 STICKERS! No Duplicates - Random Sprunki Stickers Gift S",
    "price": 5.99,
    "image": "https://i.ebayimg.com/images/g/QYwAAOSwxYhn1eEe/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168145634627",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 13,
    "name": "Shea Langeliers #305 SILVER SPARKLE - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/-BoAAeSwgHhpxckx/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265461262",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 14,
    "name": "Shohei Ohtani #RA-SO - 2026 Topps Heritage MLB Baseball Card",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/9KoAAeSwrw5pvX7Y/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313526844",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 15,
    "name": "Austin Riley #238 OPENING DAY FOIL - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/Og8AAeSwKuhpz-Kt/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313526858",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 16,
    "name": "IVYSAUR Foil PSA 8  1999 TOPPS Pokemon Movie Edition E1 Foil *BTX",
    "price": 15,
    "image": "https://i.ebayimg.com/images/g/ErQAAeSw3MRpg55J/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497245",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 17,
    "name": "Jackson Chourio - FIRST WALK OFF - 2025 MLB Topps NOW® - Card 406",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/aWsAAeSwwyNomoh4/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245432447",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 18,
    "name": "Clayton Kershaw #22 SILVER SPARKLE - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.38,
    "image": "https://i.ebayimg.com/images/g/0foAAeSw7rpp0Eap/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168285028718",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 19,
    "name": "Jose Ramirez #GD-18 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.43,
    "image": "https://i.ebayimg.com/images/g/HlwAAeSw86lpxa5X/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265265512",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 20,
    "name": "2026 Chinese Zodiac Year of the Horse Commemorative Coin Horse Design Silver",
    "price": 9,
    "image": "https://i.ebayimg.com/images/g/FQQAAeSwks1o~Ajq/s-l300.jpg",
    "url": "https://www.ebay.com/itm/167883172652",
    "category": "coins",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 21,
    "name": "Mike Trout #TOG-2 - 2026 Topps Series 1 - MLB Baseball",
    "price": 1.66,
    "image": "https://i.ebayimg.com/images/g/t4IAAeSwXMRpleNA/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168169132241",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 22,
    "name": "Kawhi Leonard #AS19 - 2025-'26 Topps Now NBA All-Star Game",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/bQsAAeSwWrVpvJUL/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168247974372",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 23,
    "name": "Jonah Tong (RC) #4 SILVER SPARKLE - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.38,
    "image": "https://i.ebayimg.com/images/g/LawAAeSwu~dp0Efe/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168285040314",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 24,
    "name": "Billy The Marlin #M-30 Marlins Mascot - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/3CcAAeSwrudpxbIa/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265302704",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 25,
    "name": "27/50* Milwaukee Brewers 14th Straight Win - 2025 MLB Topps NOW® - Card 561",
    "price": 9,
    "image": "https://i.ebayimg.com/images/g/8qoAAeSw7plot8aV/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302512529",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 26,
    "name": "Giancarlo Stanton #250 Blue Sparkle - 2026 Topps Heritage MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/oJMAAeSwY0ppweoP/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168257566557",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 27,
    "name": "Rookie Pitchers #387 Refractor - 2026 Topps Heritage MLB Baseball Card",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/lY8AAeSwVhJpvcLk/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168250095085",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 28,
    "name": "Jeremiah Fears (RC) #RS19 - 2026 NBA Castrol Rising Stars Basketball Card",
    "price": 2.14,
    "image": "https://i.ebayimg.com/images/g/eRYAAeSwjKdpv1hN/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168310663200",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 29,
    "name": "Walker Buehler LA Dodgers 2024 MLB Topps Now Card 872 World Series",
    "price": 2.25,
    "image": "https://i.ebayimg.com/images/g/TgQAAOSwQypnIU6F/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307367308",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 30,
    "name": "Darryn Peterson #12 Refractor - 2025 Topps Chrome McDonald's All American",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/aZ4AAeSwy85puf52/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168306310455",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 31,
    "name": "Los Angeles Dodgers - 2024 MLB Topps NOW® Card 820",
    "price": 5.25,
    "image": "https://i.ebayimg.com/images/g/Sc8AAOSwBWFnCE73/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245208176",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 32,
    "name": "Derek Jeter/Anthony Volpe - 2024 MLB Topps NOW® Card 878 WS",
    "price": 5.75,
    "image": "https://i.ebayimg.com/images/g/HxAAAOSwUipnIqob/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245465326",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 33,
    "name": "2026 Topps Series 1 #T91-14 Oneil Cruz Pirates '91",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/AtYAAeSwK8BpjkL8/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168155461684",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 34,
    "name": "Samuel Basallo #RA-SB - 2026 Topps Heritage MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/fwMAAeSwYB1pveBS/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168250286220",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 35,
    "name": "Jacob Misiorowski - 2025 MLB Topps NOW® - Card 349 Skenes Brewers",
    "price": 6,
    "image": "https://i.ebayimg.com/images/g/KXAAAOSwi~xoXZgD/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245348164",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 36,
    "name": "William Contreras Walk-Off - 2025 MLB Topps NOW® - Card 595 BREWERS",
    "price": 6,
    "image": "https://i.ebayimg.com/images/g/MRIAAeSwHf1oqlJW/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245436376",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 37,
    "name": "Wilyer Abreu / Ceddanne Rafaela - 2025 MLB Topps NOW® - Card 181 *IN HAND*",
    "price": 8,
    "image": "https://i.ebayimg.com/images/g/0bUAAOSwXUBoJl~Y/s-l300.jpg",
    "url": "https://www.ebay.com/itm/167516666284",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 38,
    "name": "Bobby Witt Jr. #SMLB-5 - 2026 Topps Series 1 - MLB Baseball",
    "price": 1.66,
    "image": "https://i.ebayimg.com/images/g/GCgAAeSw3etplVC1/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168168105664",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 39,
    "name": "Bryan Wood #99 Dark Gray Border - 2026 Topps Heritage MLB Baseball Card",
    "price": 3.56,
    "image": "https://i.ebayimg.com/images/g/WuMAAeSwP4ZpvWKa/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168249447765",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 40,
    "name": "2026 Topps Series 1 Andrew McCutchen 2025 Greatest Hits #GH-11 Pirates",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/jXIAAeSw-fVpjosw/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168156000507",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 41,
    "name": "Drake Baldwin #234 - Black Parallel - Topps 2025 Archives - M/NM",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/iiAAAeSwRI9pX8qt/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168306310457",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 42,
    "name": "Nick Kurtz Rookie OTY Athletics MLB - 2025 MLB Topps NOW® - Card OS-2",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/hDYAAeSwR3ppNHRb/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245582539",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 43,
    "name": "2026 Topps 1991 Jose Ramirez #T91-69 Topps Series 1 MLB Baseball",
    "price": 2.14,
    "image": "https://i.ebayimg.com/images/g/OMkAAeSwMXtpjk7l/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168155527730",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 44,
    "name": "2026 Chinese Zodiac Year of the Horse Commemorative Coin Horse Design Gold",
    "price": 9,
    "image": "https://i.ebayimg.com/images/g/DwEAAeSw8sRo~AfR/s-l300.jpg",
    "url": "https://www.ebay.com/itm/167883171360",
    "category": "coins",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 45,
    "name": "Screech #M-13 Nationals Mascot - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/puQAAeSw7rhpxbHg/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265301572",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 46,
    "name": "03/50* William Contreras #595 PARALLEL - 2025 Topps Now Brewers",
    "price": 18,
    "image": "https://i.ebayimg.com/images/g/~-IAAeSwLGBp4POx/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168312551365",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 47,
    "name": "Roman Anthony (RC) 2026 Topps Series 1 -  75th Anniversary Rookie #T91-71",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/uLAAAeSwpttpjk-7/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497251",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 48,
    "name": "20/25* Cooper Flagg PARALLEL - 2025-26 NBA Topps NOW® - Card 207 M/NM",
    "price": 86,
    "image": "https://i.ebayimg.com/images/g/WQ8AAeSwxahp2nN9/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168301978628",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 49,
    "name": "Porygon Picture Book Mini Card Japanese Nintendo Rare Pokemon A207 NM *BTX",
    "price": 49,
    "image": "https://i.ebayimg.com/images/g/U50AAeSwXlVpgr6x/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497247",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 50,
    "name": "18/25* John Blackwell Eclipses 1k - 2025-26 Bowman U NOW® Basketball Card 24",
    "price": 25,
    "image": "https://i.ebayimg.com/images/g/YugAAeSwUjZpSegl/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497256",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 51,
    "name": "31/50* AUTO RELIC Freddy Peralta 2023 Topps Pristine Around the Diamond #ADR-FP",
    "price": 29,
    "image": "https://i.ebayimg.com/images/g/D9cAAeSwTjZo4yZ0/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302497254",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 52,
    "name": "Sal Stewart (RC) - 2026 MLB Topps NOW® - Card 88 ROOKIE #auction PRE-SALE",
    "price": 0.99,
    "image": "https://i.ebayimg.com/images/g/ndkAAeSw69Jp4dhH/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313900301",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 53,
    "name": "Sal Stewart (RC) - 2026 MLB Topps NOW® - Card 88 ROOKIE PRE-SALE",
    "price": 5.94,
    "image": "https://i.ebayimg.com/images/g/ndkAAeSw69Jp4dhH/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313889082",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 54,
    "name": "27/50* Justyn-Henry Malloy #180 PARALLEL - 2025 Topps Now MLB Baseball Card",
    "price": 13.75,
    "image": "https://i.ebayimg.com/images/g/snYAAeSw~9Bp4Pbw/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168312568420",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 55,
    "name": "13/15* AUTO Sal Frelick #PA-SF1 PARALLEL - 2021 Leaf Trading Card",
    "price": 17.25,
    "image": "https://i.ebayimg.com/images/g/Mo0AAeSwPL5p4PZl/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168312562719",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 56,
    "name": "19/25* Milwaukee Brewers TO NLCS - 2025 Topps Now Baseball MLB Card",
    "price": 25,
    "image": "https://i.ebayimg.com/images/g/sncAAeSwm6Zp4PV2/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168312558569",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 57,
    "name": "107/250* DaShawn Keirsey (RC) #19 - 2025 Topps Chrome Rookie MLB Baseball Card",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/kUYAAeSwwilp4PUU/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168312557411",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 58,
    "name": "Alex Ferreira USA GOLD Freeskiing- 2026 Olympics Topps NOW® - Card 17 *SHIPS NOW",
    "price": 6.5,
    "image": "https://i.ebayimg.com/images/g/AuwAAeSwoSBpm4Ur/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168251844523",
    "category": "coins",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 59,
    "name": "Sal Stewart (RC) - 2026 MLB Topps NOW® - Card 84 ROOKIE PRE-SALE",
    "price": 6.45,
    "image": "https://i.ebayimg.com/images/g/LxYAAeSw3Hxp4BSF/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168311280937",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 60,
    "name": "AUTO Jace Jung #84FFA-JJ 2025 Topps Archives Rookie Fan Favorites Tigers",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/vbAAAeSw2XNpVBUD/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039215",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 61,
    "name": "PSA 6 - 1982 DONKEY KONG STICKERS  It'll Drive U Bananas  *BTX",
    "price": 19,
    "image": "https://i.ebayimg.com/images/g/M4QAAeSwWaZpg8Wa/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039210",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 62,
    "name": "07/10* BLACK Mikaela Shiffrin USA OLYMPICS 2026 Olympics Topps NOW® - Card 13",
    "price": 20.76,
    "image": "https://i.ebayimg.com/images/g/id8AAeSwG6dp3Pu9/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168306234437",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 63,
    "name": "Jack Hughes USA GOLDEN GOAL Hockey - 2026 Olympics Topps NOW® - Card 18 IN HAND",
    "price": 7.2,
    "image": "https://i.ebayimg.com/images/g/O~AAAeSwXMRpm1dX/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168274135164",
    "category": "hockey",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 64,
    "name": "Jacob Misiorowski RC Brewers 2026 Topps MLB Living Set Card 916 Baseball Miz",
    "price": 5.97,
    "image": "https://i.ebayimg.com/images/g/jcAAAeSw~upp1EVp/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168291658931",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 65,
    "name": "George Springer - Go Ahead HR 2025 MLB Topps NOW® - Card 888",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/nWEAAeSw-Z1o9-gG/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245758665",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 66,
    "name": "Sal Stewart (RC) - 2026 MLB Topps NOW® - Card 84 ROOKIE PRE-SALE #auction",
    "price": 4.76,
    "image": "https://i.ebayimg.com/images/g/LxYAAeSw3Hxp4BSF/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168311297161",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 67,
    "name": "PSA 5 - 1982 DONKEY KONG STICKERS  It's Better With Donkey Kong  *BTX",
    "price": 12.6,
    "image": "https://i.ebayimg.com/images/g/ztUAAeSwXwppg8Xo/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168309405626",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 68,
    "name": "Shohei Ohtani Los Angeles Dodgers 2024 MLB Topps Now 750",
    "price": 2.25,
    "image": "https://i.ebayimg.com/images/g/29wAAOSwLs5m9IEC/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357094",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 69,
    "name": "US Penny - Discontinued After 232 Years - 2025 Topps NOW® Card",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/M8oAAeSw13RpFn94/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245939743",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 70,
    "name": "Chase Burns (RC) - 2026 MLB Living Set® - Card 920 Rookie PRE-SALE",
    "price": 5.66,
    "image": "https://i.ebayimg.com/images/g/2FMAAeSwoKZp19JR/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168297773764",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 71,
    "name": "Andrew Vaughn 2nd HR Series NLDS - 2025 MLB Topps NOW® - Card 856",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/RXQAAeSw5jdo7BeF/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357095",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 72,
    "name": "39/50* Oneil Cruz - 2025 MLB Topps NOW® - Card 206 Pittsburg Pirates",
    "price": 9,
    "image": "https://i.ebayimg.com/images/g/eZwAAOSwWXtoTJkq/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039217",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 73,
    "name": "Jacob Misiorowski (RC) 11K OPENING DAY - 2026 MLB Topps NOW®  Card 4 PRE-SALE",
    "price": 6.74,
    "image": "https://i.ebayimg.com/images/g/CGkAAeSw7Axpx3H~/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168268429716",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 74,
    "name": "045/399* Joey Loperfido #263 - 2026 Topps Series 1 - MLB Baseball Card Parallel",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/nRMAAeSwqP5pxa0g/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168298292800",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 75,
    "name": "Bernie Brewer #M-5 BREWERS MASCOT - 2026 Topps Series 1 - MLB Baseball",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/lscAAeSwc~ppxctq/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265489402",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 76,
    "name": "Brice Turang 1st Postseason HR NLDS - 2025 MLB Topps NOW® - Card 857",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/fqAAAeSw8hNo7Bfc/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245438742",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 77,
    "name": "43/50* Andrew Vaughn - 2025 MLB Topps NOW® - Card 485 Milwaukee Brewers",
    "price": 7.2,
    "image": "https://i.ebayimg.com/images/g/kj8AAeSwIr1opQZC/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168228268564",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 78,
    "name": "Vladimir Guerrero Jr.  GRAND SLAM G2 - 2025 MLB Topps NOW- Card 827 *IN HAND*",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/DmcAAeSwRuVo5FNa/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313526836",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 79,
    "name": "Paul Skenes - 2024 MLB Topps NOW® Card OS-2 Rookie Of The Year ROTY",
    "price": 2.25,
    "image": "https://i.ebayimg.com/images/g/K-8AAOSwBpZnO-Ja/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357088",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 80,
    "name": "Jeremy Fears Jr. B10 History 2025-26 Bowman U NOW® Basketball Card 60",
    "price": 3.75,
    "image": "https://i.ebayimg.com/images/g/bVwAAeSwOt5peUiv/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245909358",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 81,
    "name": "Dodgers Duo Japan #265 Shohei - Fanatics Exclusive - 2026 Topps Series 1 - MLB",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/OX8AAeSw705ptd7Z/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302512535",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 82,
    "name": "Giannis Antetokounmpo - 2025-26 NBA Topps NOW® - Card 23 Bucks NBA",
    "price": 3.33,
    "image": "https://i.ebayimg.com/images/g/2-IAAeSw8Fho~Xye/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245848066",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 83,
    "name": "Quinn Priester - 2025 MLB Topps NOW® - Card 661 Milwaukee Brewers",
    "price": 7.2,
    "image": "https://i.ebayimg.com/images/g/qrQAAeSwV7JovJJL/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245363638",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 84,
    "name": "Spencer Schwellenbach #306 REFRACTOR - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/ZXwAAeSwRL1pz-I2/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168284311357",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 85,
    "name": "38/50* PARALLEL Milwaukee Brewers DIVISION CHAMPS! - 2025 MLB Topps NOW Card 746",
    "price": 9,
    "image": "https://i.ebayimg.com/images/g/bmoAAeSwIcxo6rvP/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168304898888",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 86,
    "name": "Jackson Chourio NLDS Brewers - 2025 MLB Topps NOW® - Card 818",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/-sQAAeSwSWlo4reo/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245360919",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 87,
    "name": "Milwaukee Brewers 97 WINS Record - 2025 MLB Topps NOW® - Card 794",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/eBAAAeSwyQVo2vpZ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245418957",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 88,
    "name": "William Contreras / Jackson Chourio - 2025 MLB Topps NOW® - Card 835",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/DuQAAeSwkV5o5XyE/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245368477",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 89,
    "name": "Jac Caglianone (RC) #138 REFRACTOR - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/tk8AAeSwLeFpyZWW/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357105",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 90,
    "name": "Nick Kurtz Longest HR StatCast HIstory 2025 MLB Topps NOW® - Card 711",
    "price": 4.51,
    "image": "https://i.ebayimg.com/images/g/zuMAAeSwZWZozYfz/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245775926",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 91,
    "name": "Bryce Harper 350th Home Run- 2025 MLB Topps NOW® - Card 459",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/vqUAAeSw3xpogqv-/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245608408",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 92,
    "name": "RELIC Juan Soto #CCR-JS - 2026 Topps Heritage MLB Baseball Card",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/p9AAAeSw3EZpweXs/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168304917783",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 93,
    "name": "Roman Anthony - 2026 World Baseball Classic Topps NOW® - Card 21",
    "price": 2.5,
    "image": "https://i.ebayimg.com/images/g/VlQAAeSwKO1psIfW/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357102",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 94,
    "name": "Logan Henderson - 2025 MLB Topps NOW® - Card 199 Milwaukee Brewers RC",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/gD0AAOSwuFdoLkbf/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245381625",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 95,
    "name": "Yoshinobu Yamamoto Clutch Outing - 2025 MLB Topps NOW® - Card 916",
    "price": 4.51,
    "image": "https://i.ebayimg.com/images/g/PgEAAeSwifBpBtrB/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245189941",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 96,
    "name": "Alex Freeland (RC) #8B-21 - 8 BIT BALLERS - 2026 Topps Series 1 - MLB Baseball C",
    "price": 3.33,
    "image": "https://i.ebayimg.com/images/g/umsAAeSwNtJpxcnQ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265467661",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 97,
    "name": "Luka Dončić 43Pts. 1st Gm 2025-26 NBA Topps NOW® Card 5 Lakers NBA",
    "price": 5.75,
    "image": "https://i.ebayimg.com/images/g/6DoAAeSwpGlo-Vq3/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245938557",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 98,
    "name": "Freddie Freeman #PAS-8 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.66,
    "image": "https://i.ebayimg.com/images/g/imUAAeSw59Bpxa7K/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265271622",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 99,
    "name": "Samuel Basallo (RC) #104 2026 Topps Series 1 Rookie- Sand Glitter Rainbow",
    "price": 2,
    "image": "https://i.ebayimg.com/images/g/kxMAAeSwY6Bpjo0j/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307220750",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 100,
    "name": "Steph Curry - 2024-25 Topps NOW® Basketball Card 13 - 4K 3 Pointers",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/2EwAAOSweR9n1FLA/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245940003",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 101,
    "name": "Kyle Schwarber - 2026 World Baseball Classic Topps NOW® - Card 14 IN HAND",
    "price": 7,
    "image": "https://i.ebayimg.com/images/g/FlUAAeSwDfVpry15/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168218677547",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 102,
    "name": "Aaron Judge - 2024 MLB Topps NOW® Card 837 1st HR POSTSEASON ALCS",
    "price": 6,
    "image": "https://i.ebayimg.com/images/g/LA4AAOSwh-1nEEQ5/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245470259",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 103,
    "name": "2025-26 Topps Basketball Rasheer Fleming NEW APPLICANT Rookie Auto #NA-RF",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/R~AAAeSwbatpLyrA/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168313526850",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 104,
    "name": "Chet Holmgren #AS21 - 2025-'26 Topps Now NBA All-Star Game",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/QOYAAeSwYB1pvJVN/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168247977709",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 105,
    "name": "Pokemon Pikachu Field Flowers GOLD DISPLAY Card MINT CONDITION.",
    "price": 4.08,
    "image": "https://i.ebayimg.com/images/g/AYgAAOSwphRmY4PJ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/166810253008",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 106,
    "name": "/150* Agot Makeer #55 Parallel - 2025 Topps Chrome McDonald's All American",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/A3AAAeSwtqRputUQ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168244257452",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 107,
    "name": "Truffletoot - Plushie Garten of Banban Characters Gift For Kids! ~9\\",
    "price": 34,
    "image": "https://i.ebayimg.com/images/g/EpoAAeSwS3xp18BM/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168297667603",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 108,
    "name": "Jackson Chourio #GD-15 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.43,
    "image": "https://i.ebayimg.com/images/g/IU4AAeSwsSFpxa41/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265263197",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 109,
    "name": "Dragonair 3/20 Dragon Vault Holo Rare Pokemon Card NM  *BTX",
    "price": 3,
    "image": "https://i.ebayimg.com/images/g/uIMAAeSwumNpgVgJ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168306310463",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 110,
    "name": "Aaron Judge #10 - BASE CARD - 2026 Topps Heritage MLB Baseball",
    "price": 2.38,
    "image": "https://i.ebayimg.com/images/g/U5sAAeSwFVNpxX6N/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168264891775",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 111,
    "name": "2026 Topps Series 1 #GH-27 Michael Busch Greatest Hits Cubs",
    "price": 2.14,
    "image": "https://i.ebayimg.com/images/g/lgcAAeSw1mxpjous/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168156002390",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 112,
    "name": "Jacob Misiorowski - 1st PS Win 2025 MLB Topps NOW® - Card 833",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/ZSoAAeSwhx1o5Xuo/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245446006",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 113,
    "name": "Solo Ball - 2024-25 Bowman U NOW® Basketball UConn - Card 57",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/NDcAAOSwrYFnopkX/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245944666",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 114,
    "name": "Jacob Misiorowski Miz 2nd PS Win NLDS - 2025 MLB Topps NOW Card 858",
    "price": 3.8,
    "image": "https://i.ebayimg.com/images/g/pbcAAeSwx8ho7Bct/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245428263",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 115,
    "name": "Bronny James #77 McFlurry Refractor - 2025 Topps Chrome McDonald's All American",
    "price": 7,
    "image": "https://i.ebayimg.com/images/g/4WYAAeSwTkFpugis/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168242544780",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 116,
    "name": "Haxorus 16/20 Dragon Vault Holo Rare Pokemon Card NM *C* *BTX",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/zWMAAeSwcVxpgh~i/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168302512528",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 117,
    "name": "PSA 9 Sucess #55 Topps Movie Edition 1999 Pokemon Card *BTX Charizard Arbok",
    "price": 26.1,
    "image": "https://i.ebayimg.com/images/g/5HEAAeSwjA5pg8ty/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168310618533",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 118,
    "name": "CHRIS SALE 2024 MLB Topps NOW OS4 OS-4  WINS CY YOUNG ATLANTA BRAVES",
    "price": 4.75,
    "image": "https://i.ebayimg.com/images/g/gzAAAeSwdg9o4bE3/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168245518124",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 119,
    "name": "Porygon 2 Pokemon Zukan Card Japanese Nintendo Game Rare LP *BTX",
    "price": 15,
    "image": "https://i.ebayimg.com/images/g/pVgAAeSwiONpgqXc/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039213",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 120,
    "name": "Jose Ramirez #PAS-16 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 1.66,
    "image": "https://i.ebayimg.com/images/g/3L4AAeSwdylpxa9d/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265276467",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 121,
    "name": "Milwaukee Brewers Wall Decor Old School Vintage  ~12in x 8in.  MLB Sign",
    "price": 5,
    "image": "https://i.ebayimg.com/images/g/WM8AAOSwo~doKL5Y/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168307357086",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 122,
    "name": "Cassidy Animation Series 2 PSA 8 2000 Topps Pokemon TV #HV5  *BTX",
    "price": 12.6,
    "image": "https://i.ebayimg.com/images/g/S9IAAeSwX79pg7G7/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168309405629",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 123,
    "name": "Tyrese Maxey #AS6 - 2025-'26 Topps Now NBA All-Star Game",
    "price": 3.75,
    "image": "https://i.ebayimg.com/images/g/NbEAAeSwP4ZpvJJu/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168247950204",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 124,
    "name": "Roman Anthony (RC) #86 Base  - 2026 Topps Heritage MLB Baseball Card",
    "price": 4.73,
    "image": "https://i.ebayimg.com/images/g/FecAAeSwXslpveVX/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168250326303",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 125,
    "name": "McDonald's AUTO RELIC /25* Sienna Betts #GP-SB - 2025 Topps Chrome All American",
    "price": 900,
    "image": "https://i.ebayimg.com/images/g/n8MAAeSwJWxpuf~-/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168242543072",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 126,
    "name": "Dylan Harper (RC) #RS7 - 2026 NBA Castrol Rising Stars Basketball Card",
    "price": 2.14,
    "image": "https://i.ebayimg.com/images/g/kQQAAeSwsdppv1a9/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168310637631",
    "category": "basketball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 127,
    "name": "Porygon Pokemon card game Japan Anime Very Rare Pocket monster BANDAI MP*B *BTX",
    "price": 5.99,
    "image": "https://i.ebayimg.com/images/g/UugAAeSwwdZpg5WM/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168135260328",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 128,
    "name": "[MINT] Tandemaus 055/066 - SV4M - Future Flash - C - Pokemon Card TCG - Japanese",
    "price": 1.57,
    "image": "https://i.ebayimg.com/images/g/Z8AAAOSwaXhmx89Q/s-l300.jpg",
    "url": "https://www.ebay.com/itm/166932280889",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": true
  },
  {
    "id": 129,
    "name": "Pokemon Vintage Holo Sticker Porygon No.166 1998 Made in Japan Amada LP/MP  *BTX",
    "price": 20,
    "image": "https://i.ebayimg.com/images/g/~w8AAeSwQZxpgrUn/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168315039214",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 130,
    "name": "Spencer Torkelson #106 PINK SPARKLE - 2026 Heritage - MLB Baseball Card",
    "price": 1.9,
    "image": "https://i.ebayimg.com/images/g/Ko4AAeSwzN5p3m~2/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168308674931",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 131,
    "name": "LOT OF 11 [6pcs Flat + 5pcs Pointy] Paint Brushes - Arts Crafts Gifts Painting",
    "price": 1.89,
    "image": "https://i.ebayimg.com/images/g/gOEAAOSwPNZkzcTJ/s-l300.jpg",
    "url": "https://www.ebay.com/itm/166266739465",
    "category": "other",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 132,
    "name": "Shohei Ohtani #ATT-9 - 2026 Topps Series 1 - MLB Baseball Card",
    "price": 2.85,
    "image": "https://i.ebayimg.com/images/g/gWcAAeSw4J9pyZTU/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168272010289",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 133,
    "name": "/76* Nick Pivetta #9 Independance Day - 2026 Topps Series 1 - MLB Baseball",
    "price": 4,
    "image": "https://i.ebayimg.com/images/g/UckAAeSwscxptdeS/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168306299712",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 134,
    "name": "Gunnar Henderson #GD-13 - 2026 Topps Series 1 - MLB Baseball",
    "price": 1.43,
    "image": "https://i.ebayimg.com/images/g/GsoAAeSw5o1pxc1g/s-l300.jpg",
    "url": "https://www.ebay.com/itm/168265505110",
    "category": "baseball",
    "badge": null,
    "discount": null,
    "numbered": false
  },
  {
    "id": 135,
    "name": "Pokemon Raikou EX RAINBOW DISPLAY Card MINT CONDITION",
    "price": 7.19,
    "image": "https://i.ebayimg.com/images/g/PW0AAOSwC81m7Zzx/s-l300.jpg",
    "url": "https://www.ebay.com/itm/166981910953",
    "category": "pokemon",
    "badge": null,
    "discount": null,
    "numbered": false
  }
];
